name: Docker build push and Email send

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Iamge Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd_pipeline:latest .

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd_pipeline:latest

      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: A New Feature has been added to the CI/CD Pipeline
          body: \```
            Sir Shaffay,

            Congrats!!! 🎉🎊
            ```
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
